title: My Blog
author: Joshua Hayden
email: joshhayden@domain.com
description:  > # this means to ignore newlines until "baseurl:"
  Very cool, very awesome blog

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
